### ISSUE TITLE
my test

### ISSUE THREAD

**Issue by AS400JPLPC** [mnemnion/mvzr#1]
hello 

I changed the function that produced an error during compilation
``` 
/// Match `pattern` in `haystack`.
pub fn match(haystack: []const u8, pattern: []const u8) bool {
    const maybe_regex = compile(pattern);
    if (maybe_regex) |regex| {
        const maybe_match = regex.match(haystack);
        if (maybe_match) |m| {
            if (haystack.len == m[1]) return true else return false;
        } else {
            return false ;
        }
        
    } else {
        return false;
    }
}
```

I would like it to work with this  {1,6}  thank you

``` 
const std = @import("std");

const freg = @import("mvzr");
 
pub fn main() !void {

    const regex = std.fmt.comptimePrint("^[A-Z]{s}1{s}[a-zA-Z0-9]{s}1,{d}{s}$", .{"{", "}",  "{", 6, "}" });      
    std.debug.print("patern:{s} \r\n",.{regex});
    
    const first = freg.match("Pabcex",regex) ;
    std.debug.print("mvzr Macth >{any}< \r\n",.{first}) ;
}

```
résult :
patern:^[A-Z]{1}[a-zA-Z0-9]{1,6} 
mvzr Macth >false<

I used comptime just for testing in my application, the formatting is random to test values, so I use pcre2, but I would like to only use zig

thank you

**Comment by mnemnion** [comment]
I'm seeing two feature requests here: one for the `{a,b}` repetition format, and another for a function which returns `true` or `false` if the regex matched the whole string.  Did I get that right?

The latter is pretty easy to add, but wouldn't be called `match`.  The library is still developing somewhat rapidly, and `match` is about to return a `Match` object with `.slice`, `.start`, and `.end` fields, or `null`, to be consistent with the recently added `regex.iterator(haystack)` function. 

I'll have to think about how this should work. My first thought is that, as a boolean, it should be `regex.isMatch(haystack)`. 

That wouldn't check to see if it matched the whole string, because if you need that, you can use `^<<whatever>>$`, and it will only succeed if the whole string matches. 

Did I get the gist of it?

>  I would like to only use zig

That's the idea!

**Comment by AS400JPLPC** [comment]
```
const regex = "[A-Za-z]$"; this OK

const first = freg.match("Pabcex",regex) ;
std.debug.print("mvzr Macth >{any}< \r\n",.{first}) ;   // true

```



```
 // decimal unsigned  scal > 0
  std.debug.print("Macth decimal unsigned  scal > 0 {} \r\n",.{reg.isMatch(
  "12345.02",
  std.fmt.allocPrint(allocatorPrint,
   "^[0-9]{s}1,{d}{s}[.][0-9]{s}{d}{s}$",.{"{",width,"}","{",scal,"}"}
  ) catch unreachable)});
```

So that you can better understand, here, I check the input integrity of a field with pcre2
and my software creates the pattern automatically based on the definition of the input widget.

I hope my English is understandable


[program-test pcre2](https://github.com/AS400JPLPC/zig_regex/blob/master/src-zig/testreg.zig)

**Comment by mnemnion** [comment]
Check out `v0.0.4` release, it adds an `isMatch` method and the `{M,N}` style of qualifier.  Also makes `*`, `+`, `?` behave the way people have come to expect them to. 

Let me know if that's what you had in mind.

**Comment by AS400JPLPC** [comment]
I gave you a test so you can understand what's not working
[library.tar.gz](https://github.com/user-attachments/files/16263697/library.tar.gz)
put everything in the Zmvzr folder

**Comment by AS400JPLPC** [comment]
[src-zig.tar.gz](https://github.com/user-attachments/files/16263703/src-zig.tar.gz)

for folder Zmvzr

**Comment by mnemnion** [comment]
Looking through your tests I see you used the /g flag. `mvzr` doesn't have flags and probably won't.

Then again, `/g` isn't needed: without anchors, `mvzr` will search for a match anywhere in a string, and it matches newlines with `.` (any one byte).

To make life a bit easier, please post future test cases in a simple code block or gist, something like this:

```zig
const std  = @import("std");
const testing = @import ("testing");

const mvzr = @import("mvzr);
const compile = mvzr.compile;

test "failing (?) test case" {
    const abc_end = compile("[A-Za-z]$").?;
    try testing.expect(abc_end.isMatch("Pabcex"));
}
```
That way I can drop the test into the file and try it (this passes).

**Comment by AS400JPLPC** [comment]
Yes, I removed it, the functions that are not working are in comments

**Comment by mnemnion** [comment]
Please try the latest release, `v0.0.7`.  If there are still failing tests you'd like to bring to my attention, please provide them as part of the issue, using [this code snippet](https://github.com/mnemnion/mvzr/issues/1#issuecomment-2233468469) as a template, and I'll see what I can do.

**Comment by AS400JPLPC** [comment]
```
  "10/12/1951",
  "(0[1-9]|1[012])[\\/](0[1-9]|[12][0-9]|3[01])[\\/][0-9]{4}")});
```

Almost everything works;

I found the error,
"(0[1-9]|[12][0-9]|3[01])"
as soon as there are more than 2 choices it bugs
error
mvzr.zig:1230:21: 0x1044a21 in compile (testmvzr)
                sets[s] = CharSet{ .low = low, .hi = hi };
date-iso 



```
 "1951-02-29",
    "([0-9]{4}[-/]?((0[13-9]|1[012])[-]?(0[1-9]|[12][0-9]|30)|(0[13578]|1[02])[-]?31|02[-]?(0[1-9]|1[0-9]|2[0-8]))|([0-9]{2}(([2468][048]|[02468][48])|[13579][26])|([13579][26]|[02468][048]|0[0-9]|1[0-6])00)[-]?02[-]?29)"
```    
    
Same for ISO date check

Afterwards, I think I have covered the standard usage

everything passes except the date check

it's a standard and I checked with
https://www.regextester.com/

https://stackoverflow.com  standard DATE

[testmvzr.txt](https://github.com/user-attachments/files/16277416/testmvzr.txt)




```
Macth A-Z false 

log p1  ^[A-Z]{1,1}[a-zA-Z0-9]{0,}$/g
MVZR  A-Z false 
Macth abc true 

log p1  ^[a-zA-Z]{1,1}[a-zA-Z0-9]{0,}$
MVZR abc true 
Macth digit true 

log 423  ^[1-9]{1}[0-9]{2,2}$
MVZR digit true 
Macth tel frtrue 
reached
log +(33)6.12.34.56.78  [+][(][0-9]{2,3}[)][0-9]([-.0-9]{1,3}){1,4}
MVZR tel frtrue 
Macth tel ustrue 
reached
log +(001)456.123.789.123  [+][(][0-9]{3}[)][0-9]{3}([-.][0-9]{3}){1,4}
MVZR tel ustrue 
Macth date frtrue 
Macth date ustrue 
Macth date isotrue 
Macth Mailtrue 

log myname.myfirst_name@gmail.com  [a-zA-Z0-9_!#$%&.-]+@([a-zA-Z0-9.-])+
MVZR Mailtrue 
Macth digit unsignedtrue 

log 123  ^[0-9]{1,5}$
MVZR digit unsignedtrue 
Macth digit true 

log +12345  ^[+-][0-9]{1,5}$
MVZR digit false 
Macth decimal unsigned  scal = 0 true 

log 12345  ^[0-9]{1,5}$
MVZR decimal unsigned  scal = 0 true 
Macth decimal unsigned  scal > 0 true 

log 12345.02  ^[0-9]{1,5}[.][0-9]{2}$
MVZR decimal unsigned  scal > 0 false 
Macth decimal signed  scal = 0 true 

log +12345  ^[+-][0-9]{1,5}$
MVZR decimal signed  scal = 0 false 
Macth decimal signed  scal > 0 true 

log +12345.02  ^[+-][0-9]{1,5}[.][0-9]{2}$
MVZR decimal signed  scal > 0 false 
-----------------------
Macth 1951-02-29 date isofalse 
Macth A-Z true 

log 😀P😀  ^😀[A-Z0-9]{1,2}😀$
MVZR A-Z true 
```

**Comment by AS400JPLPC** [comment]
Thank you very much for everything you do.

**Comment by mnemnion** [comment]
```text
  "10/12/1951",
  "(0[1-9]|1[012])[\\/](0[1-9]|[12][0-9]|3[01])[\\/][0-9]{4}")});
```
Thanks, this turned up a bug: The compile function was accepting one less character set than promised.  `Regex` is actually a `SizedRegex(64,8)`, and this pattern has exactly eight character sets, but the compiler was only accepting 7: a `>=` which should have been a `>`. 

The hard limit is 256 character sets, because the offset into the sets is stored in a `u8`.  But if you get an "excessive number of" error, you can figure out what size of `SizedRegex` you need, at comptime, like this:

```zig
    const patt = "(0[1-9]|1[012])[\\/](0[1-9]|[12][0-9]|3[01])[\\/][0-9]{4}";
    const j, const s = mvzr.resourcesNeeded(patt);  // patt must be comptime-known
    std.debug.print("ops: {d}, sets {d}", .{ j, s });
    const ProperlySizedRegex = mvzr.SizedRegex(j, s);
    // now you can do this:
    const the_regex = ProperlySizedRegex.compile(patt);
```
I suggest that once a regex stabilizes, you print out the values returned from `resourcesNeeded`, and add them directly to the program.  Otherwise you'll be `comptime` parsing the regex string every time you compile, and comptime is not that fast yet. 

You can also use this to make the struct for a given regex pattern fit exactly, although making a type for every regex will bloat the binary somewhat, so there's a balance to be struck there. 

`v0.0.10` will have a fix for the one-short character set problem. Thanks for your report.

**Comment by mnemnion** [comment]
Hmm, no, it turns out that the problem was with the `resourcesNeeded` function, which was reporting the maximum, not the ordinal value. Since offsets start from zero, this was one short, so you'll need a custom SizedRegex to handle this. 

You'll also need `v0.0.10`, because handling a SizedRegex which isn't the default one turned up some bugs in the function signatures for dispatch functions.  I'll let you know when that happens.

**Comment by mnemnion** [comment]
`v0.10.0` fixes the test case two ways. 

First, a `SizedRegex` which isn't identical to the default `Regex` now actually, uh, works. 

Second, the compiler deduplicates non-unique character sets.  The example has nine sets, but only six unique ones, so it now fits in the default `Regex` struct, a `SizedRegex(64,8)`. 

I'll leave the issue open for awhile, in case you hit more failing cases. Cheers.

**Comment by AS400JPLPC** [comment]
last function , if you feel like doing it
the ISO standard
 // https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression
 // chapter RFC 6532 updates 5322 to allow and include full, clean UTF-8.
 
One more last problem certain character does not pass, from : ``` '*+\\/=?`{|}~^ ``` 
This standard was reduced to the "oreilly" form 
```
"myname.myfirstname@gmail.com",
  "[a-zA-Z0-9_!#$%&'*+\\/=?`{|}~^.-]+@[a-zA-Z0-9.-]+")});
```

the original form subject to bugs and too complex has been abandoned.
for information:

[mail.txt](https://github.com/user-attachments/files/16302471/mail.txt)



Otherwise everything is operational, thank you great work.


My email check:
 ``` [a-zA-Z0-9_!#$%&.-]+@([a-zA-Z0-9.-]) ```

proof that it works, and I took into account SizedRegex

[testmvzr.txt](https://github.com/user-attachments/files/16303653/testmvzr.txt)

**Comment by AS400JPLPC** [comment]
This is just my opinion:
Fluent does a lot of things outside of regex, but a comptime regex is not in the direction of meta programming practice, I thank you for doing this work, I'm starting to get tired, 73 years old, I've done a lot thing and I brought my stone (IBM) and had a lot of fun, I will be able to finish my code generator (designer) type screen 5250/3270 and have everything in ZIG a hobby that I had in my head this will allow to do business management at a lower cost (machine) and which exists under UNIX / AS400, but not available on Linux.
Thanks again...

**Comment by AS400JPLPC** [comment]
just tested the Oreilly email

now nothing to envy PCRE2 / fluent for regex and it suits me

**Comment by mnemnion** [comment]
Alright, we'll close this one then. If you hit upon a regex string that you think should work, feel free to reopen.

**Comment by mnemnion** [comment]
I closed this a bit too quickly 😅

`v0.1.1` fixes the email string test, which passes now (and will live in the test suite henceforth).
