### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by RetroDev256** [mnemnion/mvzr#2]
Thank you for the wonderful library! It is really enjoyable to use. I have been trying to use it with a terminal project of mine, where I expect the user to input regex expressions as part of the interface. Unfortunately I have noticed that you use std.log to report errors, and it clutters my program output (which is also my UI). Is it possible that you could adjust the library so I can disable error logging, or possibly report errors another way?

**Comment by neurocyte** [comment]
You should capture log output in your application with a custom logging function by declaring a `std_options` struct in your root module. Then you can do what ever you want with it. Or just ignore it.

Here is an example of how this is done: https://github.com/neurocyte/flow/blob/2b90fe66e85791120558d084e651e0d142281b2a/src/main.zig#L22

**Comment by mnemnion** [comment]
I had a note in the source code to change this behavior at some point, but it looks like I removed it.  

The question on the table is whether compiling should look like this:

```zig
const a_regex = Regex.compile(a_regex_string) catch |err| {
     // Switch statement on RegexCompileError error set
};
```
The current behavior is that it compiles or it doesn't, and if it doesn't, it logs an error message.   That *is* a deliberate choice, which favors using `mvzr` as an internal library, because that means it's just 

```zig
const known_regex = Regex.compile(known_string).?;
```
Where you get a panic if the regex is wrong. For 'internal' use of this nature, it's easy enough to fix that.  For [ohsnap](https://github.com/mnemnion/ohsnap) logging is the optimal behavior, but I see why that might not always be true.

If `compile` is error-returning, then users have to choose between polluting the error set of functions which compile a regex, or sprinkling `catch unreachable;` everywhere.   I would want to provide distinct errors based on what fails, but it's unclear what a switch statement based on those distinctions would accomplish.

But the fact is that compiling a regex does have error states, so one could argue that its more honest, in a sense, to return those states as defined errors.  This decision is complicated by the fact that Zig errors can't carry payloads (which has always been a mixed bag), and the most important fact about a failed regex is what character it fails on, so I would still want to report that, which means logging of some sort. 

@neurocyte is correct that the logging framework is under your control, so maybe that's the answer here.  It wouldn't be much work to add a build option to `mvzr` which suppresses logging, either. 

I'm glad you're getting good use out of `mvzr` ^_^ I'll leave this issue open for awhile for feedback / discussion of the options, since I don't have a strong sense yet of what's the best move.

**Comment by neurocyte** [comment]
I'd say logging is the right solution either way.

A. If the regex being compiled is a static part of the the program, logging should be rare and really only a debugging tool.
B. If the regex is user input, you'll want to log an user visible error with the application's usually logging functionality and return a programatic error to stop whatever functionality was trying to make use of the regex.

In either case a regular log message seems like a perfectly fine way to communicate the problem.

**Comment by mnemnion** [comment]
I think that's basically right.  I'll keep thinking about the error vs. optional question. The only error states in the compiler are variations on "we are unable to turn this into a regex", but there's at least two distinct categories: the string is malformed, or the `SizedRegex` is too small to contain the compiled VM code and sets. 

I'm still leaning toward the current behavior, which is that you either get a Regex back or you don't, and if not, check the logs. I can at least imagine that someone might want an `error.RegexTypeTooSmall` so they can size a new type accordingly, but when I think about what that code would really entail, probably not, because the type values have to be comptime-known.  The friction on using an optional is quite a bit lower, so I'll most likely stick with the status quo there. 

Taking at look at your code in `flow`, and reading up a bit on `std.log`, I'll definitely want to add a custom logging scope, so that it can be easily filtered out without having to decide to exclude the default scope.  That shouldn't be much work at all, I can probably find an hour or two to write and test that over the weekend.

**Comment by mnemnion** [comment]
Release [v0.2.2](https://github.com/mnemnion/mvzr/releases/tag/v0.2.2) moves logging to the `.mvzr` scope, where it's easy for a custom logger to filter out. 

@RetroDev256 that should cover your use case.
